language: php

php:
  - "7.2"
  - "7.3"

install:
  - pecl install -f mongodb-1.5.3 ast-1.0.1 redis-4.3.0
  - composer install

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage-clover.xml

branches:
  only:
    - master
